# Generated by Django 4.2.16 on 2026-07-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier PDF')),
                ('taille_fichier', models.PositiveIntegerField(default=0, editable=False, verbose_name='Taille du fichier (Ko)')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('nombre_telechargements', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de téléchargements')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents_app.categoriedocument', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_publication'],
            },
        ),
    ]
