# Generated by Django 4.2.16 on 2026-07-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='bi-check-circle', help_text='Exemple : bi-search, bi-mortarboard, bi-people', max_length=60, verbose_name='Classe icône (Bootstrap Icons)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Objectif spécifique',
                'verbose_name_plural': 'Objectifs spécifiques',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='ParametresSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisation', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('sigle', models.CharField(blank=True, max_length=30, verbose_name='Sigle / Acronyme')),
                ('devise', models.CharField(default='Mieux savoir pour mieux agir.', max_length=255, verbose_name='Devise')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('histoire', models.TextField(blank=True, verbose_name="Histoire de l'organisation")),
                ('mission', models.TextField(verbose_name='Mission')),
                ('vision', models.TextField(verbose_name='Vision')),
                ('objectif_general', models.TextField(blank=True, verbose_name='Objectif général')),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Image de la section d'accueil (Hero)")),
                ('texte_hero', models.CharField(blank=True, max_length=255, verbose_name="Texte d'accroche (Hero)")),
                ('texte_appel_action', models.CharField(blank=True, default="Rejoignez-nous dans la promotion des droits de l'enfant en Haïti", max_length=255, verbose_name="Texte de l'appel à l'action")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Exemple : Recherches publiées', max_length=150, verbose_name='Libellé')),
                ('valeur', models.PositiveIntegerField(help_text='Exemple : 25', verbose_name='Valeur')),
                ('suffixe', models.CharField(blank=True, help_text='Exemple : +, %', max_length=10, verbose_name='Suffixe')),
                ('icone', models.CharField(default='bi-graph-up', max_length=60, verbose_name='Classe icône (Bootstrap Icons)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='ValeurOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la valeur')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(default='bi-star', max_length=60, verbose_name='Classe icône (Bootstrap Icons)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Valeur de l'organisation",
                'verbose_name_plural': "Valeurs de l'organisation",
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
