# Generated by Django 4.2.16 on 2026-07-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('duree', models.CharField(help_text='Exemple : 3 jours, 20 heures', max_length=100, verbose_name='Durée')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('intervenant', models.CharField(max_length=255, verbose_name='Intervenant(e)')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/images/', verbose_name='Image')),
                ('places_disponibles', models.PositiveIntegerField(default=0, verbose_name='Places disponibles')),
                ('inscriptions_ouvertes', models.BooleanField(default=False, verbose_name='Inscriptions ouvertes')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation / Institution')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Inscription à une formation',
                'verbose_name_plural': 'Inscriptions aux formations',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddConstraint(
            model_name='inscriptionformation',
            constraint=models.UniqueConstraint(fields=('formation', 'email'), name='inscription_unique_par_formation'),
        ),
    ]
