# Generated by Django 4.2.16 on 2026-07-28 15:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de recherche',
                'verbose_name_plural': 'Catégories de recherche',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('auteur', models.CharField(max_length=255, verbose_name='Auteur(s)')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('contenu', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Contenu détaillé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recherches/images/', verbose_name='Image de couverture')),
                ('fichier_pdf', models.FileField(upload_to='recherches/pdf/', verbose_name='Fichier PDF')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('nombre_telechargements', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de téléchargements')),
                ('est_mise_en_avant', models.BooleanField(default=False, verbose_name="Mise en avant sur la page d'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherches', to='recherches.categorierecherche', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Recherche',
                'verbose_name_plural': 'Recherches',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['-date_publication'], name='recherches__date_pu_460cf2_idx')],
            },
        ),
    ]
